# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(help_text='Name of the Person making the testimonial (max. 255 characters)', max_length=255, verbose_name='Name of the Person')),
                ('person_image', models.ImageField(max_length=255, upload_to='testimonials/', verbose_name='Image of the Person')),
                ('image_licence', models.CharField(help_text='Make sure you hold the copyrights for the image', max_length=255, verbose_name='Licence/Credentials for the image')),
                ('title', models.CharField(help_text='Name of the Person making the testimonial (max. 255 characters)', max_length=255, verbose_name='Title of the Testimonial')),
                ('title_en', models.CharField(help_text='Name of the Person making the testimonial (max. 255 characters)', max_length=255, null=True, verbose_name='Title of the Testimonial')),
                ('title_de', models.CharField(help_text='Name of the Person making the testimonial (max. 255 characters)', max_length=255, null=True, verbose_name='Title of the Testimonial')),
                ('title_pt', models.CharField(help_text='Name of the Person making the testimonial (max. 255 characters)', max_length=255, null=True, verbose_name='Title of the Testimonial')),
                ('title_es', models.CharField(help_text='Name of the Person making the testimonial (max. 255 characters)', max_length=255, null=True, verbose_name='Title of the Testimonial')),
                ('content', models.TextField(help_text='The quoted part of the testimonial (max. 2000 characters)', max_length=1000, verbose_name='Content of the Testimonial')),
                ('content_en', models.TextField(help_text='The quoted part of the testimonial (max. 2000 characters)', max_length=1000, null=True, verbose_name='Content of the Testimonial')),
                ('content_de', models.TextField(help_text='The quoted part of the testimonial (max. 2000 characters)', max_length=1000, null=True, verbose_name='Content of the Testimonial')),
                ('content_pt', models.TextField(help_text='The quoted part of the testimonial (max. 2000 characters)', max_length=1000, null=True, verbose_name='Content of the Testimonial')),
                ('content_es', models.TextField(help_text='The quoted part of the testimonial (max. 2000 characters)', max_length=1000, null=True, verbose_name='Content of the Testimonial')),
                ('published', models.BooleanField(default=False, help_text='If the testimonial is published', verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
