# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180906_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='content_de',
            field=models.TextField(help_text='The quoted part of the testimonial (max. 2000 characters)', max_length=1000, null=True, verbose_name='Content of the Testimonial'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_en',
            field=models.TextField(help_text='The quoted part of the testimonial (max. 2000 characters)', max_length=1000, null=True, verbose_name='Content of the Testimonial'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_es',
            field=models.TextField(help_text='The quoted part of the testimonial (max. 2000 characters)', max_length=1000, null=True, verbose_name='Content of the Testimonial'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_pt',
            field=models.TextField(help_text='The quoted part of the testimonial (max. 2000 characters)', max_length=1000, null=True, verbose_name='Content of the Testimonial'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title_de',
            field=models.CharField(help_text='Name of the Person making the testimonial (max. 255 characters)', max_length=255, null=True, verbose_name='Title of the Testimonial'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title_en',
            field=models.CharField(help_text='Name of the Person making the testimonial (max. 255 characters)', max_length=255, null=True, verbose_name='Title of the Testimonial'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title_es',
            field=models.CharField(help_text='Name of the Person making the testimonial (max. 255 characters)', max_length=255, null=True, verbose_name='Title of the Testimonial'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title_pt',
            field=models.CharField(help_text='Name of the Person making the testimonial (max. 255 characters)', max_length=255, null=True, verbose_name='Title of the Testimonial'),
        ),
    ]
