# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.CharField(help_text='Say what you can share!', max_length=500, verbose_name='Sharing Pitch')),
                ('active', models.BooleanField(default=True, help_text='If the sharing offer is active and not yet satisfied', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Sharing Offer',
                'verbose_name_plural': 'Sharing Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callout', models.CharField(help_text='Say what you need!', max_length=255, verbose_name='Sharing Callout')),
                ('sharetype', models.PositiveSmallIntegerField(choices=[(1, 'Lend an Item'), (2, 'Share an Item'), (3, 'Give an Item'), (4, 'Provide a Service'), (5, 'Join an Event')], default=1, help_text='For which kind of sharing is this Sharing Request intended?', verbose_name='Kind of Sharing')),
                ('share_start', models.DateTimeField(blank=True, help_text='When do you want to start?', null=True, verbose_name='Start Sharing')),
                ('share_end', models.DateTimeField(blank=True, help_text='When do you want to end?', null=True, verbose_name='End Sharing')),
                ('active', models.BooleanField(default=True, help_text='If the sharing request is active and not yet satisfied', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('area', models.ForeignKey(help_text='Area for the sharing request', max_length=255, on_delete=django.db.models.deletion.PROTECT, to='utils.Area')),
            ],
            options={
                'verbose_name': 'Sharing Request',
                'verbose_name_plural': 'Sharing Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title Description of the Item, Service or Event (max. 255 characters)', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Long Description of the Item, Service or Event (max. 2000 characters)', max_length=2000, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stuff/', verbose_name='Image')),
                ('sharetype', models.PositiveSmallIntegerField(choices=[(1, 'Lend an Item'), (2, 'Share an Item'), (3, 'Give an Item'), (4, 'Provide a Service'), (5, 'Join an Event')], default=1, help_text='For which kind of sharing is this Stuff available?', verbose_name='Kind of Sharing')),
                ('active', models.BooleanField(default=True, help_text='If the Item or Service is generally available', verbose_name='Active')),
                ('location_independent', models.BooleanField(default=False, help_text='If the Item or Service is not dependent on its location', verbose_name='Location Independent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('address', models.ForeignKey(help_text='Location (Address & Area) the Item or Service is located', on_delete=django.db.models.deletion.PROTECT, related_name='stuff', to='utils.Address')),
                ('owner', models.ForeignKey(help_text='Owner of the Item or Service', on_delete=django.db.models.deletion.PROTECT, related_name='owned_stuff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stuff',
                'verbose_name_plural': 'Stuff',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sharingrequest',
            name='stuff',
            field=models.ForeignKey(blank=True, help_text='Stuff this Sharing Request relates to. (Optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sharing_requests', to='market.Stuff'),
        ),
        migrations.AddField(
            model_name='sharingrequest',
            name='user',
            field=models.ForeignKey(help_text='User who issued the sharing request', on_delete=django.db.models.deletion.PROTECT, related_name='sharing_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharingoffer',
            name='request',
            field=models.ForeignKey(blank=True, help_text='Sharing Request this Sharing Offer relates to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sharing_offers', to='market.SharingRequest'),
        ),
        migrations.AddField(
            model_name='sharingoffer',
            name='stuff',
            field=models.ForeignKey(help_text='Stuff this Sharing Offer relates to', on_delete=django.db.models.deletion.PROTECT, related_name='sharing_offers', to='market.Stuff'),
        ),
        migrations.AddField(
            model_name='sharingoffer',
            name='user',
            field=models.ForeignKey(help_text='User emitting this Sharing Offer', on_delete=django.db.models.deletion.PROTECT, related_name='sharing_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
