# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('pt', 'Portuguese'), ('es', 'Spanish')], default='en', help_text='Which language would you like to use?', max_length=255, verbose_name='Application Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='User Account of this Profile', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
