# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180906_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(blank=True, help_text='Your Main Address', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_address', to='position.Address'),
        ),
    ]
