# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 07:48
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0041_auto_20180908_0748'),
        ('auth', '0008_alter_user_username_max_length'),
        ('userprofile', '0003_auto_20180906_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalProfile',
            fields=[
                ('owner', models.OneToOneField(help_text='User Account of this Internal Profile', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='internal_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_subscription_type', models.PositiveSmallIntegerField(choices=[(0, 'No Account'), (1, 'Free Account'), (2, 'Paid Account')], default=1, help_text='Free or Paid Account', verbose_name='Type of current subscribtion')),
                ('subscription_from', models.DateTimeField(blank=True, null=True, verbose_name='Starting Date & Time of current subscription')),
                ('subscription_to', models.DateTimeField(blank=True, null=True, verbose_name='Ending Date & Time of current subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Internal Profile',
                'verbose_name_plural': 'Internal Profiles',
            },
        ),
        migrations.CreateModel(
            name='PrivateProfile',
            fields=[
                ('owner', models.OneToOneField(help_text='User Account of this Private Profile', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='private_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('pt', 'Portuguese'), ('es', 'Spanish')], default='en', help_text='Which language would you like to use?', max_length=255, verbose_name='Application Language')),
                ('email', models.EmailField(help_text='Your email address to reach out to you.', max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Your phone number to reach out to you.', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email_reminder', models.BooleanField(default=True, help_text='If you want a notification per Email about what other people offer and search in your area', verbose_name='Email Reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('main_address', models.OneToOneField(blank=True, help_text='Your Main Address', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_address', to='position.Address')),
            ],
            options={
                'verbose_name': 'Private Profile',
                'verbose_name_plural': 'Private Profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Public Profile', 'verbose_name_plural': 'Public Profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Say something about yourself.', max_length=1000, null=True, verbose_name='Short Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, help_text='How other Users see you.', null=True, upload_to='profile/', verbose_name='Your Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='User Account of this Public Profile', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='public_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
