# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0041_auto_20180908_0748'),
        ('userprofile', '0005_auto_20180908_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateprofile',
            name='current_area',
            field=models.ForeignKey(blank=True, help_text='Area you currently are observing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='position.Area'),
        ),
    ]
