# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0045_auto_20180911_0800'),
        ('userprofile', '0006_privateprofile_current_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='privateprofile',
            name='app_lang',
            field=models.ForeignKey(blank=True, help_text='Which language would you like to use in the App?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_profiles', to='position.Language'),
        ),
    ]
