# Generated by Django 2.0.3 on 2018-09-01 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='', max_length=255, verbose_name='Street')),
                ('street_number', models.CharField(help_text='', max_length=55, verbose_name='Street Number')),
                ('supplement', models.CharField(blank=True, help_text='', max_length=255, null=True, verbose_name='Address Supplements')),
                ('zipcode', models.CharField(blank=True, help_text='', max_length=55, null=True, verbose_name='Zip Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['street', 'street_number'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Country the Area is located in.', max_length=255, verbose_name='Country')),
                ('region', models.CharField(blank=True, help_text='Region the Area is located in.', max_length=255, null=True, verbose_name='Region')),
                ('city', models.CharField(help_text='City the Area is located in.', max_length=255, verbose_name='City')),
                ('verified', models.BooleanField(default=False, help_text='If the specified area is verified to be existent and relevant', verbose_name='Verified Area')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['country', 'city'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.ForeignKey(help_text='Owner of the Item or Service', on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='position.Area'),
        ),
    ]
