# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0043_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='country',
            field=models.CharField(blank=True, help_text='Name of the Country. Ex.: Australia', max_length=100, null=True, verbose_name='Country'),
        ),
    ]
