# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0044_auto_20180911_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='country_de',
            field=models.CharField(blank=True, help_text='Name of the Country. Ex.: Australia', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='language',
            name='country_en',
            field=models.CharField(blank=True, help_text='Name of the Country. Ex.: Australia', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='language',
            name='country_es',
            field=models.CharField(blank=True, help_text='Name of the Country. Ex.: Australia', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='language',
            name='country_pt',
            field=models.CharField(blank=True, help_text='Name of the Country. Ex.: Australia', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_de',
            field=models.CharField(help_text='Name of the Language. Ex.: English', max_length=100, null=True, verbose_name='Language Name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(help_text='Name of the Language. Ex.: English', max_length=100, null=True, verbose_name='Language Name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_es',
            field=models.CharField(help_text='Name of the Language. Ex.: English', max_length=100, null=True, verbose_name='Language Name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_pt',
            field=models.CharField(help_text='Name of the Language. Ex.: English', max_length=100, null=True, verbose_name='Language Name'),
        ),
    ]
