# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0045_auto_20180911_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.RemoveField(
            model_name='area',
            name='city',
        ),
        migrations.RemoveField(
            model_name='area',
            name='country',
        ),
        migrations.RemoveField(
            model_name='area',
            name='region',
        ),
        migrations.AddField(
            model_name='area',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='name',
            field=models.CharField(default='default', help_text='Name of Area in the hierarchy. E.g.: City or Country', max_length=255, verbose_name='Area Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='position.Area'),
        ),
        migrations.AddField(
            model_name='area',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
