# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 07:53
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0046_auto_20180917_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='adjacent_areas',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, related_name='_area_adjacent_areas_+', to='position.Area'),
        ),
    ]
