# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 09:32
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0047_area_adjacent_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='geobox_center',
            field=geoposition.fields.GeopositionField(blank=True, help_text='Centered Geoposition (latitude and longitude) of the Area', max_length=42, null=True, verbose_name='Centered Geoposition'),
        ),
        migrations.AddField(
            model_name='area',
            name='geobox_upper',
            field=geoposition.fields.GeopositionField(blank=True, help_text='Lower-Right Geoposition (latitude and longitude) of the Area', max_length=42, null=True, verbose_name='Lower-Right Geoposition Boundary'),
        ),
        migrations.AlterField(
            model_name='area',
            name='adjacent_areas',
            field=mptt.fields.TreeManyToManyField(help_text='Areas that are neighbors or subsets of this area.', related_name='_area_adjacent_areas_+', to='position.Area'),
        ),
    ]
