# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 09:33
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0048_auto_20180917_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='geobox_lower',
            field=geoposition.fields.GeopositionField(blank=True, help_text='Lower-Right Geoposition (latitude and longitude) of the Area', max_length=42, null=True, verbose_name='Lower-Right Geoposition Boundary'),
        ),
        migrations.AlterField(
            model_name='area',
            name='geobox_upper',
            field=geoposition.fields.GeopositionField(blank=True, help_text='Upper-Left Geoposition (latitude and longitude) of the Area', max_length=42, null=True, verbose_name='Upper-Left Geoposition Boundary'),
        ),
    ]
