# Generated by Django 2.0.3 on 2018-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0002_auto_20180806_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
    ]
