# Generated by Django 2.0.3 on 2018-08-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0003_stuff_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='sharetype',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
    ]
