# Generated by Django 2.0.3 on 2018-08-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0004_stuff_sharetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='sharetype',
            field=models.CharField(choices=[('1', 'Lend'), ('2', 'Share'), ('3', 'Join'), ('4', 'Sell')], default='1', max_length=255, verbose_name='Type of Sharing'),
        ),
    ]
